#!/usr/bin/env python

import collections
import functools
import logging
import os
import re
import sys
from pprint import pprint as pp

import numpy as np
import pytutils.log

pytutils.log.configure()

log = logging.getLogger(__name__)


turns = [1,2,16,19,18,0]
# turns = [1,3,2]
# turns = [2,1,3]
# turns = [0, 3, 6]
sturns = set(turns[:-1])

is_start = True

for nidx in range(len(turns), 2020):
    # log.debug('turns=%r', turns)

    last = turns[nidx-1]
    n = nidx + 1
    log.warn('n=%r last=%r', n, last)

    if last not in turns[:-1]:
        val = 0

        log.info('[unseen] val=%r', val)
    else:
        prevs = []

        for tidx, t in enumerate(turns[::-1]):
            # log.debug('tidx=%r t=%r', tidx, t)
            if is_start and tidx == 0:
                # log.debug('tidx=%r t=%r cont', tidx, t)
                continue

            if t == last:
                # log.debug('tidx=%r t=%r break', tidx, t)
                prevs.append(tidx+1)

                if len(prevs) == 2:
                    break

        log.debug('prevs=%r', prevs)

        val = prevs[1] - prevs[0]
        log.info('[seen] val=%r', val)

    is_start = False
    turns.append(val)
    sturns.add(val)

