#!/usr/bin/env python

import collections
import functools
import logging
import operator
import os
import random
import re
import string
import sys
import typing as T
from dataclasses import dataclass
from pprint import pprint as pp

import ipdb
import numpy as np

import attr
import IPython
import pytutils.log

pytutils.log.configure()

log = logging.getLogger(__name__)

challenge_name = os.path.basename(sys.argv[0])
challenge_shortname = challenge_name.split('-')[0]
log.info('challenge: %s short=%s', challenge_name, challenge_shortname)


def slurp(fn: str):
    log.info('reading fn=%s', fn)
    with open(fn) as fh:
        raw_lines = fh.readlines()

    lines = []
    for line in raw_lines:
        log.debug('line=%r', line)
        line = line.strip().rstrip('\n').rstrip()

        if not line or line.startswith('#'):
            continue
        lines.append(line)

    return lines


suffix = '-part2-test'
# suffix = '-test'

fn = './%s.input%s' % (challenge_shortname, suffix)
answers_fn = './%s.answers%s' % (challenge_shortname, suffix)
lines = slurp(fn)
answers = slurp(answers_fn)
